font_size 12
font_family JetBrains Mono
background #1e1e2e
foreground #cdd6f4
selection_background #45475a
selection_foreground #cdd6f4
url_color #89b4fa
cursor #f5e0dc
cursor_text_color #1e1e2e

active_border_color #89b4fa
inactive_border_color #313244
bell_border_color #f9e2af

tab_bar_style powerline
tab_bar_edge top
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 8.0
tab_separator " |"

shell_integration enabled
confirm_os_window_close 0
